apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnetOLD311024
  janus-idp.io/tekton: dotnetOLD311024
  backstage.io/kubernetes-id: dotnetOLD311024
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnetOLD311024
resources:
- deployment.yaml
- route.yaml
- service.yaml
